### ISSUE TITLE
Ideas for making the Gherkin more natural

### ISSUE THREAD

**Issue by kevgo** [Originate/cukelib#1]
From `Feature: Super Simple Echo Server`:

- use `When` instead of `Given` for making the call
- make steps read more like proper English
- don't put quotes around numbers, they don't have spaces in them

```cucumber
  Scenario: A GET call just responds
    When making a GET request to "/users"
    Then the API responds with status code 200


  Scenario: A PUT call echos its input body
    When making a PUT to "/losers" with the payload:
      """
      [
        "Sally Sad",
        "Billy Bad"
      ]
      """
    Then the API responds with the status code 200 and the payload:
      """
      [
        "Sally Sad",
        "Billy Bad"
      ]
      """

**Comment by mjhm** [comment]
Thanks @kevgo.  The 1st and 3rd points were good catches. The 2nd point also -- but the extremely terse step definitions were a [conscious choice](https://github.com/Originate/cukelib#step-definitions-conventions).  I used your example above to show [how to easily use customized step definitions](https://github.com/Originate/cukelib/blob/master/customization.md) and added an [apology](https://github.com/Originate/cukelib/blob/master/customization.md#apology-for-my-gherkin-abuse).

**Comment by kevgo** [comment]
In my opinion, the right course of action, according to what you document, is to provide good, readable, and self-explaining step definitions that work for as many people as possible out of the box. Then provide the option for users to define their own custom and terse versions if they want to. 

The current terse steps don't work for most people, codify a Gherkin anti-pattern (not writing understandable steps, using broken English and grammar errors), and are therefore misleading. They also don't allow using Gherkin for documentation, preventing one of the reasons to use it in the first place. One shouldn't use Gherkin at all then imo.

Maybe export both types of steps from your library. But I would strongly recommend using readable steps in your documentation. It really helps somebody new to this library understand what you are documenting and testing there.
